FROM python:3.11.10-slim-bullseye

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./run_prod.sh /app/run_prod.sh

COPY . /app

RUN chmod +x /app/run_prod.sh

EXPOSE 8000

CMD ["bash", "/app/run_prod.sh"] 